AuCal/config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :librarians

  devise_for :users
  root 'home#index'

  get 'home/schedule'

  get 'sessions/new'
  resources :sessions, only: :index
  get "/auth/:provider/callback" => 'sessions#create'

  get 'calendar/index'

end

AuCal/app/models/appointment.rb
class Appointment < ActiveRecord::Base
	
end

AuCal/app/models/calendar.rb
class Calendar < ActiveRecord::Base
	@cal = 'helllo'
end

AuCal/app/models/librarian.rb
class Librarian < ActiveRecord::Base
	has_many :appointments
	@lib = Librarian.all
	def lib_appoints

	end
end

AuCal/app/models/token.rb
class Token < ActiveRecord::Base
end

AuCal/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

AuCal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

AuCal/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:time, :day, :librarian_email)
    end
end

AuCal/app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	def index
	end
end

AuCal/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def schedule
		render 'schedule.html.erb'
	end
end

AuCal/app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.all
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def librarian_params
      params.require(:librarian).permit(:name, :email)
    end
end

AuCal/app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def new
  end

  def create
    @auth = request.env['omniauth.auth']['credentials']
    Token.create(
      access_token: @auth['token'])
 end
end

AuCal/app/helpers/application_helper.rb
module ApplicationHelper
end

AuCal/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

AuCal/app/helpers/calendar_helper.rb
module CalendarHelper
end

AuCal/app/helpers/home_helper.rb
module HomeHelper
end

AuCal/app/helpers/librarians_helper.rb
module LibrariansHelper
end

AuCal/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class="field">
	  <%=f.label :librarian %></br>
    <%= f.collection_select(:librarian_email, Librarian.all, :email, :name) %>
    <br/></br>
  <div class="actions">
    <%= f.submit "Create Appointment", class: 'btn btn-primary' %>
  </div>
<% end %>

AuCal/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

AuCal/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Day</th>
      <th>Librarian Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.time %></td>
        <td><%= appointment.day %></td>
        <td><%= appointment.librarian_email %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

AuCal/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

AuCal/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Day:</strong>
  <%= @appointment.day %>
</p>

<p>
  <strong>Librarian:</strong>
  <%= @appointment.librarian_email %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'View Appointments', appointments_path %>

AuCal/app/views/calendar/index.html.erb
<p> hey </p>
<p><%=@cal%></p>

AuCal/app/views/home/_calendar.html.erb
<style>

#calendar table {
	border-collapse: collapse;
	width: 100%;
}

#calendar td:hover{
	color: #FF0000;
}
#calendar td,
#calendar th {
	font-family: "Lucida Grande",arial,helvetica,sans-serif;
	font-size: 10px;
	padding: 6px;
	border: 1px solid #999;
}

#calendar th {
	background: #DDD;
	color: #666;
	text-align: center;
	width: 14.2857142857143%;
}

#calendar td {
	background: #FFF;
	color: #777;
	height: 80px;
	vertical-align: top;
	font-size: 16px;
}

#calendar .notmonth {
	color: #CCC;
}

#calendar #month {
	margin: 0;
	padding-top: 10px;
	padding-bottom: 10px;
	text-align: center;
}

#calendar #month a, #calendar #month a:hover {
	text-decoration: none;
	padding: 0 10px;
	color: #FF0000;
}

#calendar .today {
	background-color: #D7F2FF;
}

#calendar ul {
	margin: 0;
	margin-top: 5px;
	padding: 0;
	list-style: none;
}

#calendar li {
	margin: 0;
	padding: 0;
	font-size: 11px;
	text-align: center;
}
</style>
<table id='calendar'>
<tr>
<th>Sunday</th><th>Monday</th>
<th>Tuesday</th><th>Wednesday</th>
<th>Thursday</th><th>Friday</th>
<th>Saturday</th>
</tr>
<tr>
<% @beginning_of_month = Date.civil(2009, 12, 1) %>
<% @end_of_month = Date.civil(2009, 12, -1) %>

<% (@beginning_of_month..@end_of_month).each do |d| %>
	<% if d == @beginning_of_month %>
		<% d.wday.times do %> <td class='offset'></td> <% end %>
	<% end %>

	<% if d.wday == 0 %> </tr><tr> <% end %>
	<td> <%= d.day %> </td>
<% end %>
</tr>
</table>

AuCal/app/views/home/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'AU Librarian Calendar', root_path, class: 'navbar-brand' %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if !user_signed_in? %>
				<li><%= link_to 'Login', new_user_session_path %></li>
				<li><%= link_to 'Register', new_user_registration_path %></li>

			<% else %>
				<li><%= link_to current_user.email, root_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %></li>
			<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

AuCal/app/views/home/index.html.erb
<style> 






@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css);
body { padding-top: 0px; }
.nav.nav-justified > li > a { position: relative; }
.nav.nav-justified > li > a:hover,
.nav.nav-justified > li > a:focus { background-color: transparent; }
.nav.nav-justified > li > a > .quote {
	position: absolute;
	left: 0px;
	top: 0;
	opacity: 0;
	width: 30px;
	height: 30px;
	padding: 5px;
	background-color: #13c0ba;
	border-radius: 15px;
	color: #fff;  
}
.nav.nav-justified > li.active > a > .quote { opacity: 1; }
.nav.nav-justified > li > a > img { box-shadow: 0 0 0 5px #13c0ba; }
.nav.nav-justified > li > a > img { 
	max-width: 100%; 
	opacity: .3; 
	-webkit-transform: scale(.8,.8);
	transform: scale(.8,.8);
	-webkit-transition: all 0.3s 0s cubic-bezier(0.175, 0.885, 0.32, 1.275);
	transition: all 0.3s 0s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.nav.nav-justified > li.active > a > img,
.nav.nav-justified > li:hover > a > img,
.nav.nav-justified > li:focus > a > img { 
	opacity: 1; 
	-webkit-transform: none;
	transform: none;
	-webkit-transition: all 0.3s 0s cubic-bezier(0.175, 0.885, 0.32, 1.275);
	transition: all 0.3s 0s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.tab-pane .tab-inner { padding: 30px 0 20px; }

@media (min-width: 768px) {
	.nav.nav-justified > li > a > .quote {
		left: auto;
		top: auto;
		right: 20px;
		bottom: 0px;
	}  
}









</style>
<div class="jumbotron" style="background-image: url(http://libraries.adelphi.edu/files/2014/03/Header6.jpg); background-size: cover; ">
	<h1>Welcome!</h1>
	<p>Here you can schedule an appointment with any of our librarians.</p>
	<% if user_signed_in? %>
	<p><%= link_to 'Schedule an appointment', new_appointment_path, class: 'btn btn-success btn-lg' %></p>
<% else %>
	<p><%= link_to 'Schedule an appointment', new_user_session_path, class: 'btn btn-success btn-lg' %></p>
<% end %>
</div>


<div class="[ container text-center ]">
	<div class="[ row ]">
		<div class="[ col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 ]" role="tabpanel">
			<div class="[ col-xs-4 col-sm-12 ]">
				<!-- Nav tabs -->
				<ul class="[ nav nav-justified ]" id="nav-tabs" role="tablist">
					<li role="presentation" class="active">
						<a href="#mike" aria-controls="mike" role="tab" data-toggle="tab">
							<img class="img-circle" src="https://avatars1.githubusercontent.com/u/5640057?v=3&s=460" />
							<span class="quote"><i class="fa fa-quote-left"></i></span>
						</a>
					</li>
					<li role="presentation" class="">
						<a href="#dave" aria-controls="dave" role="tab" data-toggle="tab">
							<img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrink_120_120/p/4/005/024/24e/2c05d8c.jpg" />
							<span class="quote"><i class="fa fa-quote-left"></i></span>
						</a>
					</li>
					<li role="presentation" class="">
						<a href="#matt" aria-controls="matt" role="tab" data-toggle="tab">
							<img class="img-circle" src="https://pbs.twimg.com/profile_images/481312672407760896/eptU_-E_.jpeg" />
							<span class="quote"><i class="fa fa-quote-left"></i></span>
						</a>
					</li>
					<li role="presentation" class="">
						<a href="#coffee" aria-controls="coffee" role="tab" data-toggle="tab">
							<img class="img-circle" src="http://imgur.com/d85JOPi.jpg" />
							<span class="quote"><i class="fa fa-quote-left"></i></span>
						</a>
					</li>
				</ul>
			</div>
			<div class="[ col-xs-8 col-sm-12 ]">
				<!-- Tab panes -->
				<div class="tab-content" id="tabs-collapse">            
					<div role="tabpanel" class="tab-pane fade in active" id="mike">
						<div class="tab-inner">                    
							<p class="lead">I am a librarian at Adelphi University. I specialize in topics A and B.</p>
							<hr>
							<p><strong class="text-uppercase">Michael Vessia, Librarian for a day.</strong></p>
							<p><em class="text-capitalize"> Senior librarian</em> at <a href="http://www.adelphi.edu">Adelphi</a></p>                 
						</div>
					</div>

					<div role="tabpanel" class="tab-pane fade" id="dave">
						<div class="tab-inner">
							<p class="lead">I am also a librarian at Adelphi University.  I specialize in C and D.</p>
							<hr>
							<p><strong class="text-uppercase">David Brosnan, totally a librarian.</strong></p>
							<p><em class="text-capitalize">Librarian</em> at <a href="http://www.adelphi.edu">Adelphi</a></p>
						</div>
					</div>

					<div role="tabpanel" class="tab-pane fade" id="matt">
						<div class="tab-inner">
							<p class="lead">I am the third librarian at Adelphi University. I specialize in E and F.</p>
							<hr>
							<p><strong class="text-uppercase">Matthew Matero, definitely a librarian too.</strong></p>
							<p><em class="text-capitalize">Librarian</em> at <a href="http://www.adelphi.edu">Adelphi</a></p>
						</div> 
					</div>

					<div role="tabpanel" class="tab-pane fade" id="coffee">
						<div class="tab-inner">
							<p class="lead">I am coffee.  I was vital to getting this website working.</p>
							<hr>
							<p><strong class="text-uppercase">Coffee is love. Coffee is life.</strong></p>
						</div> 
					</div>
							

AuCal/app/views/home/schedule.html.erb
<%= render 'home/calendar'%>

AuCal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AuCal</title>
		<link rel="shortcut icon" href="http://admissions.adelphi.edu/wp-content/themes/adelphi.edu/img/apple-touch-icon.png"/>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>



		<div class="container"
			<%= render 'home/header' %>
      <div id="flash">
			<% flash.each do |name,msg| %>
				<a class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag(:div,msg,class:"alert alert-info") %>
			<%end%>
      </div>
			<%= yield %>
		</div>
	</body>


	<script type="text/javascript">
$(document).ready(function(){
	setTimeout(function(){
		$('#flash').remove();
	}, 3000);
})
$(function() {
	$('#flash').delay(500).fadeIn('normal', function() {
		$(this).delay(1500).fadeOut();
	});
});
	</script>
</html>

AuCal/app/views/librarians/_form.html.erb
<%= form_for(@librarian) do |f| %>
  <% if @librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% @librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>gi
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AuCal/app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'form' %>

<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>

AuCal/app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Librarians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Librarian', new_librarian_path %>

AuCal/app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form' %>

<%= link_to 'Back', librarians_path %>

AuCal/app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @librarian.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @librarian.email %>
</p>

<%= link_to 'Edit', edit_librarian_path(@librarian) %> |
<%= link_to 'Back', librarians_path %>